import bcrypt from 'bcryptjs';
const data = {
	users: [
		{
			name: 'Валерия',
			email: 'admin@example.com',
			password: bcrypt.hashSync('123456'),
			isAdmin: true,
		},
		{
			name: 'Антон',
			email: 'user@example.com',
			password: bcrypt.hashSync('123456'),	
			isAdmin: false,
		},
	],
	banners: [
		{
			image: '/images/banner1.jpeg',
			title: 'Новое поступление игристого вина',
			description: 'Вино рубинового цвета. В аромате тона ягод, черных фруктов, мака, сдобы. Во вкусе вино мягкое, бархатистое, с длительным фруктовым послевкусием.',
			link: '/product/f_style_w',
			button_text: 'Смотреть',
			link_all_banner: false,
		},
		{
			image: '/images/banner2.jpg',
			title: 'В нашем магазине вы найдете вино на любой вкус',
			description: '',
			link: '/search?category=вино',
			button_text: 'Смотреть',
			link_all_banner: true,
		}
	],
    products: [
        {
			name: "Fanagoria, Selfie White Semi-Sweet",
			slug: "selfie",
			category: "вино",
			color: "белое",
			volume: 0.75,
			percentage: 11,
			sort: "Цитронный маргача",
			country: "Россия",
			shugar: "полусладкое",
			description: "Цвет вина соломенный. В аромате тона цитрусовых фруктов, лепестков розы, пряные ноты. Вкус свежий, хорошо сбалансированный.",
			price: 790,
			new_price: 0,
			image: '/images/2.png',
			brand: 'Selfie',
			countInStock: 1000,
			show_main: true,
			popular: true,
			new_products: true,
		},
		{
			name: "Fanagoria, F-Style Merlot",
			slug: "f_style_w",
			category: "вино",
			color: "красное",
			volume: 0.75,
			percentage: 13,
			sort: "Мерло",
			country: "Россия",
			shugar: "сухое",
			description: "Вино рубинового цвета. В аромате тона ягод, черных фруктов, мака, сдобы. Во вкусе вино мягкое, бархатистое, с длительным фруктовым послевкусием.",
			price: 649,
			new_price: 0,
			image: '/images/3.jpeg',
			brand: 'F-Style',
			countInStock: 1000,
			show_main: true,
			popular: false,
			new_products: true,
		},
		{
			name: "Brule Cabernet Franc",
			slug: "f_style_b",
			category: "вино",
			type_product: 'игристое',
			color: "белое",
			volume: 0.75,
			percentage: " 10,0 - 12,5",
			sort: "Каберне фран",
			country: "Россия",
			shugar: "полусухое",
			description: "Вино имеет благородный розовый цвет. \nИгра мелкодисперсная, среднеинтенсивная, с выраженной насыщенностью. \nАромат - яркий, ягодный, с тонкими оттенками клубники, малины и кизила. \nВкус свежий, хорошо сбалансированный. \nПослевкусие – длительное ягодное.",
			price: 890,
			new_price: 0,
			image: '/images/4.jpeg',
			brand: 'Brule',
			countInStock: 1000,
			show_main: false,
			popular: false,
			new_products: true,
		},
		{
			name: "Коньяк F-Style, 5 лет",
			slug: "f_style_k",
			category: "коньяк",
			volume: 0.375,
			percentage: 40,
			sort: "Шардоне,Алиготе",
			country: "Россия",
			shugar: "сухое",
			description: "Коньяк имеет янтарный цвет с золотистым оттенком. В букете хорошо сочетаются тона выдержки в дубе с оттенками увяленных фруктов (абрикоса, чернослива) и легкими ванильными нотками. Вкус экстрактивный, мягкий с длительным ореховым послевкусием.",
			price: 1090,
			new_price: 0,
			image: '/images/1.jpeg',
			brand: 'F-Style',
			countInStock: 1000,
			show_main: true,
			popular: false,
			new_products: true,
		},
		{
			name: "Водка виноградная «РКАЦИТЕЛИ»",
			slug: "f_style_v",
			category: "водка",
			volume: 0.5,
			percentage: 40,
			sort: "Ркацители",
			country: "Россия",
			shugar: "сухое",
			description: "Цвет – платиновый с жемчужным оттенком. Аромат – яркий, с тонами полевых трав и цветов, в обрамлении - фруктовые оттенки груши, айвы и яблока.Вкус – мягкий, округлый с длительным плодовым послевкусием.",
			price: 970,
			new_price: 0,
			image: '/images/5.jpeg',
			brand: 'Fanagoria',
			countInStock: 1000,
			show_main: true,
			popular: true,
			new_products: true,
		}
      ],
	gastronomy: [
		{
			name: 'Сыр Шараповский',
			slug: 'sir_sharapov',
			category: 'Сыры',
			image: '/images/sharapovskiy.jpeg',
			price: 342,
			new_price: 0,
			brand: 'ВЕЛЕМИ',
			countInStock: 10,
			description: 'Сыр «Шараповский» - твердый выдержанный сыр, изготовленный в России из пастеризованного коровьего и козьего молока по рецепту сыроварни «ВЕЛЕМИ». Сыр обладает насыщенным вкусом  с небольшим послевкусием козьего молока. Зреет от одного года до полутора лет и по мере созревания приобретает все более острый вкус.',
			composition: 'молоко коровье 50% и козье 50%, соль, молокосвертывающий ферментный препарат растительного происхождения, закваска молочнокислых бактерий.',
			shelf_life: '',
			storage_rules: '',
			weight: '100',
			weight_unit: 'г.',
			country: 'Россия',
			appearance: '',
			color: '',
			product_date: ''
		},
		{
			name: 'Икра паюсная "Астраханка"',
			slug: 'astrahanka',
			category: 'Икры',
			image: '/images/ikra.jpeg',
			price: 6900,
			new_price: 0,
			brand: '',
			countInStock: 10,
			description: 'Эта паюсная икра создана по оригинальной астраханской технологии: икру-сырец обрабатывают в теплом подсоленном водном растворе – тузлуке, затем подсушивают для удаления влаги и прессуют. Обращаем внимание, что паюсная икра представляет собой однородную пастообразную массу, что и отличает ее от зернистой икры.',
			composition: 'икра осетра, соль',
			storage_rules: '24 месяца при температуре –2 – 4°С',
			shelf_life: 'до 9 марта 2023 г.',
			weight: '120',
			weight_unit: 'г.',
			country: 'Россия, Вологодская область',
			appearance: 'однородная спрессованная масса',
			color: 'насыщенный черный',
			product_date: ''
		},
		{
			name: 'Хамон 5J Иберико Бейота 36мес',
			slug: 'hamon',
			category: 'Хамоны',
			image: '/images/hamon.png',
			price: 89000,
			new_price: 0,
			brand: '5J',
			countInStock: 10,
			description: 'Уникальный по вкусу, неимоверно ароматный и бесспорно полезный, испанский Хамон – настоящее лакомство для настоящих гурманов. Обладая гармоничным вкусом, Хамон Иберико Бейота по праву считается одним из наилучших мясных деликатесов в мире. Изготовленный из мяса иберийской свиньи, приготовленный с соблюдением всех рецептурных норм и провяленный в течение 36 месяцев, хамон из Испании украсит Ваш стол.',
			composition: 'это 100% иберийская раса, свободный выпас животных и  желудевый откорм',
			storage_rules: 'Срок хранения данного продукта составляет 12 месяцев при поддержании температурного режима от +5 до +25 С',
			shelf_life: '',
			weight: '7,5-8',
			weight_unit: 'кг.',
			country: 'Sanchez Romero Carvajal, Jabugo, Huelva. Испания',
			appearance: '',
			color: '',
			product_date: ''
		}
	]
  };
  
  export default data;