import bcrypt from 'bcryptjs';
const data = {
	users: [
		{
			name: 'Валерия',
			email: 'admin@example.com',
			password: bcrypt.hashSync('123456'),
			isAdmin: true,
		},
		{
			name: 'Антон',
			email: 'user@example.com',
			password: bcrypt.hashSync('123456'),	
			isAdmin: false,
		},
	],
    products: [
        {
			name: "Fanagoria, Selfie White Semi-Sweet",
			slug: "selfie",
			category: "вино",
			color: "белое",
			volume: 0.75,
			percentage: 11,
			sort: "Цитронный маргача",
			country: "Россия",
			shugar: "полусладкое",
			description: "Цвет вина соломенный. В аромате тона цитрусовых фруктов, лепестков розы, пряные ноты. Вкус свежий, хорошо сбалансированный.",
			price: 790,
			image: '/images/2.png',
			brand: 'Selfie',
			countInStock: 1000,
			show_main: true,
			popular: true,
			new_products: true,
		},
		{
			name: "Fanagoria, F-Style Merlot",
			slug: "f_style_w",
			category: "вино",
			color: "красное",
			volume: 0.75,
			percentage: 13,
			sort: "Мерло",
			country: "Россия",
			shugar: "сухое",
			description: "Вино рубинового цвета. В аромате тона ягод, черных фруктов, мака, сдобы. Во вкусе вино мягкое, бархатистое, с длительным фруктовым послевкусием.",
			price: 649,
			image: '/images/3.jpeg',
			brand: 'F-Style',
			countInStock: 1000,
			show_main: true,
			popular: false,
			new_products: true,
		},
		{
			name: "Brule Cabernet Franc",
			slug: "f_style_b",
			category: "вино",
			type_product: 'игристое',
			color: "белое",
			volume: 0.75,
			percentage: " 10,0 - 12,5",
			sort: "Каберне фран",
			country: "Россия",
			shugar: "полусухое",
			description: "Вино имеет благородный розовый цвет. \nИгра мелкодисперсная, среднеинтенсивная, с выраженной насыщенностью. \nАромат - яркий, ягодный, с тонкими оттенками клубники, малины и кизила. \nВкус свежий, хорошо сбалансированный. \nПослевкусие – длительное ягодное.",
			price: 890,
			image: '/images/4.jpeg',
			brand: 'Brule',
			countInStock: 1000,
			show_main: false,
			popular: false,
			new_products: true,
		},
		{
			name: "Коньяк F-Style, 5 лет",
			slug: "f_style_k",
			category: "коньяк",
			volume: 0.375,
			percentage: 40,
			sort: "Шардоне,Алиготе",
			country: "Россия",
			shugar: "сухое",
			description: "Коньяк имеет янтарный цвет с золотистым оттенком. В букете хорошо сочетаются тона выдержки в дубе с оттенками увяленных фруктов (абрикоса, чернослива) и легкими ванильными нотками. Вкус экстрактивный, мягкий с длительным ореховым послевкусием.",
			price: 1090,
			image: '/images/1.jpeg',
			brand: 'F-Style',
			countInStock: 1000,
			show_main: true,
			popular: false,
			new_products: true,
		},
		{
			name: "Водка виноградная «РКАЦИТЕЛИ»",
			slug: "f_style_v",
			category: "водка",
			volume: 0.5,
			percentage: 40,
			sort: "Ркацители",
			country: "Россия",
			shugar: "сухое",
			description: "Цвет – платиновый с жемчужным оттенком. Аромат – яркий, с тонами полевых трав и цветов, в обрамлении - фруктовые оттенки груши, айвы и яблока.Вкус – мягкий, округлый с длительным плодовым послевкусием.",
			price: 970,
			image: '/images/5.jpeg',
			brand: 'Fanagoria',
			countInStock: 1000,
			show_main: true,
			popular: true,
			new_products: true,
		}
      ],
  };
  
  export default data;